#Variable that contain twitter credentials to access Twitter API.

ACCESS_TOKEN = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx"
ACCESS_TOKEN_SECRET = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
CONSUMER_KEY = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXx"
CONSUMER_SECRET = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
